### PR TITLE
Modification for using VMWare official VMTools & repo

### PR DESCRIPTION
**Pull request by agauthier51**
This adds balooning stats for example...

### CODE REVIEW

**Comment by resmo** [comment]
Thanks for the PR.

I see some improvements for this change:

These changes will not work on VMs already having open-vm-tools installed. What do you think of making it configurable by params what vmware tools package you want to have installed?

Further you removed the service part, I don't see any use case you don't want to ensure vmware tools not to be running. According my research, the `service` is named `vmware-tools-services` for official vmware tools. I would say you can make a param `use_official_vmwaretools`

~~~puppet
if $use_official_vmwaretools {
  $vmware_tools_pkg = 'vmware-tools-esx-nox'
  $vmware_tools_service = 'vmware-tools-services'
} else {
  $vmware_tools_pkg = 'open-vm-tools'
  $vmware_tools_service = 'vmtoolsd'
}
~~~

So you were able to configure what vmware-tools you want to use and where,

**Comment by agauthier51** [comment]
Hello René,

vmware-tools-services is not an init.d service, there is no chkconfig 
parameter in it and it is now started using Upstart.

But it's possible to simulate a vmtoolsd service with it running such 
command (I used it on our platform):
# sed -n 1p /etc/vmware-tools/init/vmware-tools-services > 
/etc/init.d/vmtoolsd ; echo '# chkconfig: 2345 15 85' >> 
/etc/init.d/vmtoolsd ; tail -n +2 
/etc/vmware-tools/init/vmware-tools-services >> /etc/init.d/vmtoolsd

About a test for openvm-tools, I would prefer testing if OpenVM-Tools 
are installed, and in this case remove them, as the official VMWare 
Tools are the prefered option for a better control of the platform.

On our platform I ran ansible with an rpm -e before running puppet for 
deploying the official VMWare Tools, let say it was a personal option ;)

Regards,
Arnaud

Le 09. 03. 15 10:44, René Moser a écrit :
> Thanks for the PR.
>
> I see some improvements for this change:
>
> These changes will not work on VMs already having open-vm-tools
> installed. What do you think of making it configurable by params what
> vmware tools package you want to have installed?
>
> Further you removed the service part, I don't see any use case you don't
> want to ensure vmware tools not to be running. According my research,
> the |service| is named |vmware-tools-services| for official vmware
> tools. I would say you can make a param |use_official_vmwaretools|
>
> if  $use_official_vmwaretools  {
>    $vmware_tools_pkg  ='vmware-tools-esx-nox'
>    $vmware_tools_service  ='vmware-tools-services'
> }else  {
>    $vmware_tools_pkg  ='open-vm-tools'
>    $vmware_tools_service  ='vmtoolsd'
> }
>
> So you were able to configure what vmware-tools you want to use and where,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swisstxt/puppet-platform-services/pull/5#issuecomment-77824421>.
>

-- 
Arnaud Gauthier
Consultant
Kalyss S.A.
rue Peillonnex 39
CH-1225 Chêne-Bourg

**Comment by resmo** [comment]
Hi Arnaud, 

It is fine if you can handle the migration from open-vm-tools to vmware-tools but also think about other UEs already having open-vm-tools installed.  What do you think about a63399e164bc3da5d4cd4e72391f66a69112eda8 ?

**Comment by Jefl** [comment]
Hi, it's fine for us to be able to choose.
Regards,

Jef

**Comment by agauthier51** [comment]
After upgrading to latest commit:
Error: Could not apply complete catalog: Found 1 dependency cycle:
(Augeas[yumrepo: skip_if_unavailable] => Package[open-vm-tools] => Yum::Repo[vmware-tools] => Yumrepo[vmware-tools] => Package[open-vm-tools])
Try the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz

**Comment by resmo** [comment]
@agauthier51 can you try take the yum part into `platform_services_yum` just like you did in 861b6eafad9a0643afdc72e26e15660db3ce930d?

**Comment by sontags** [comment]
Issue resolved by pull request #8

**Pull request closed without merging**
